### ISSUE TITLE
installation of deepregression package

### ISSUE THREAD

**Issue by wxhmath** [davidruegamer/deepregression#29]
When I installed deepregression package, an error occurred, how should I solve it.Please give me some advice,thanks.

keras::install_keras()
Error installing package(s): ""tensorflow==2.8.*"", ""tensorflow-hub"", ""scipy"", ""requests"", ""Pillow"", ""h5py"", ""pandas""
Warning message:
In shell(fi) :
'C:\Users\ADMINI~1\AppData\Local\Temp\RtmpkJFdQ4\file15881d5d4101.bat'

**Comment by davidruegamer** [comment]
Duplicated with [NASL Issue 8](https://github.com/neural-structured-additive-learning/deepregression/issues/8) and this version of deepregression is no longer maintained.
